export const RECORDS_LIST_REQUEST = 'RECORDS_LIST_REQUEST'
export const RECORDS_LIST_SUCCESS = 'RECORDS_LIST_SUCCESS'
export const RECORDS_LIST_FAIL = 'RECORDS_LIST_FAIL'

export const RECORDS_DETAILS_REQUEST = 'RECORDS_DETAILS_REQUEST'
export const RECORDS_DETAILS_SUCCESS = 'RECORDS_DETAILS_SUCCESS'
export const RECORDS_DETAILS_FAIL = 'RECORDS_DETAILS_FAIL'
